export component BorderlessWindow inherits Window{
    no-frame: true;
    min-width: 200px;
    min-height: 200px;

    property <bool> title-bar-pressed: false;

    callback close();
    callback move();

    VerticalLayout {
        padding: 0;

        // Title Bar
        Rectangle {
            height: 32px;
            background: lightgray;
            HorizontalLayout {
                padding-right: 7px;
                padding-left: 7px;


                Text {
                    text: root.title;
                    font-size: 13pt;
                    color: black;
                    TouchArea {
                        moved => {
                            if (root.title-bar-pressed) {
                                move();
                            }
                        }
                        pointer-event(ev) => {
                            title-bar-pressed = (ev.kind == PointerEventKind.down) && (ev.button == PointerEventButton.left);
                        }
                    }
                }

                Rectangle {
                    y: parent.height/2 - self.height/2;
                    width: parent.height * 0.75;
                    height: parent.height * 0.75;
                    closeBtn_ta := TouchArea {
                        clicked => { close() }
                    }
                    Text {
                        text: "X";
                        color: closeBtn_ta.has-hover? closeBtn_ta.pressed? black: red : black;
                        animate color {
                            duration: 250ms;
                        }
                    }
                }
            }
        }
        Rectangle {
            background: black;
            @children
        }
    }
}

export component MainWindow inherits BorderlessWindow {
    title: "Borderless Test";
    width: 360px;
    height: 480px;

    callback close-window();
    callback move-window();

    close => {
        close-window();
    }

    move() => {
        move-window();
    }
}